### ISSUE TITLE
Create GET: get next n images ID's

### ISSUE THREAD

**Issue by duanitamir** [loychris/image-labeler-app#88]

**Comment by antoniapriesnitz** [comment]
Is this supposed to replace the get next n images route or is it a new route?

**Comment by duanitamir** [comment]
ca. 1.5Hrs
Problems with the returning values, eventually changed the way i handled the search

FOR NEXT TIME:
Better use of the docs will accelerate the process of the data
finding a more suitable find method will do most of the work in the database
