### ISSUE TITLE
Create UPDATE: vote for image by ID

### ISSUE THREAD

**Issue by duanitamir** [loychris/image-labeler-app#89]
Probably exist in other form of route (PATCH image)
Modify + write in  docs

Add to the response 
the next image with this label which was not label and not in fetched list (user obj)
Add acheivments notification (string which one? ).

**Comment by antoniapriesnitz** [comment]
Since this requires auth middleware I should not use findByIdAndUpdate, right? Can I use findById, change the object and save?

**Comment by duanitamir** [comment]
Yes please, the findbyidandupdate will skip the middleware and will go directly to the database and apply the cahanges, if we first find the item, then updating it and then save it, we will forced the middleware to be applied.

**Comment by duanitamir** [comment]
5 min.
Was already implemented in the last sprint, adjust it to the requirements of frontend
