### ISSUE TITLE
Create menu-component

### ISSUE THREAD

**Issue by loychris** [loychris/image-labeler-app#9]
Responsive menu, that can be opened closed and navigated. Will be used for user menu and uploader menu.  (user-menu options: e.g. 'My achievements', 'high score', 'delete my account', ...; uploader-menu options: delete account, )  

needed time: 2 h

**Comment by mbnbln** [comment]
"Delete Account" habe ich als Option zunächst in das User Menu aufgenommen. Ich würde diese Option aber später in die User Profile Seite integrieren – nicht dass noch jemand versehentlich sein Profil löscht ;)
