### ISSUE TITLE
Create GET: get top n rating Users

### ISSUE THREAD

**Issue by duanitamir** [loychris/image-labeler-app#90]
Get users with most labels (highscore)

**Comment by duanitamir** [comment]
expected response : 

   res: [
        { "name": "Tamir", "imagesLabeled": 4301 },
        { "name": "Chris", "imagesLabeled": 2500 },
        ...
    ]

**Comment by antoniapriesnitz** [comment]
Unfinished. Does not yet send back names and highscore, but whole user objects. 1 hour 10 minutes.

**Comment by antoniapriesnitz** [comment]
Changed it to send back the names and score of the users. Another 45 minutes.
